### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by yaronelh**
Added a detailed explanation within the text to complement the one in the code expanding on the key binding structure

### CODE REVIEW

**Comment by btsdev** [comment]
Hi @yaronelh,

Looking over the suggested changes in your PR, it looks like they're somewhat redundant with what's already explained in the Python comments on lines 87 through 101. 

It might make sense to replace these comments with your explanation, but to have lines 103 through 107 follow it up, to ensure explanation of the hotkey syntax (notably keychords) and the usefulness of the `actuate_on_partial_release_flag` flag.

**Comment by yaronelh** [comment]
I rewrote it and placed it outside because usually explanations in GitHub are not strictly isolated to the code itself, rather it's a mix that complement each other. A copy of the explanation can be in the code itself, but also somewhere in the actual readme It's better to have an explanation as well. In any case, just feel free to merge it and do whatever changes you think is appropriate. 👍

**Comment by btsdev** [comment]
Thanks @yaronelh, you're absolutely right on this. Sorry, battling with the flu at the moment. I looked through your changes again and I like them. Your PR is now merged in. I may go in and update the wording later, but it looks fine to me.

Thanks so much for your contribution! Feel free to submit any other ideas you have as well. I'm admittedly a bit slow to respond sometimes (life is busy these days, putting aside fighting the flu), but I'll respond when I can. Thanks again!

**Comment by btsdev** [comment]
Also, when I'm feeling better I'll try to get this updated on PyPI as well.

**Comment by yaronelh** [comment]
Glad it helped, be well 🙂

**Pull request merged**
